export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAILURE = 'FETCH_PHONES_FAILURE';


export const FETCH_PHONE_BY_ID_START = 'FETCH_PHONE_BY_ID_START';
export const FETCH_PHONE_BY_ID_SUCCESS = 'FETCH_PHONE_BY_ID_SUCCESS';
export const FETCH_PHONE_BY_ID_FAILURE = 'FETCH_PHONE_BY_ID_FAILURE';

export const SEARCH_PHONE_START = 'SEARCH_PHONE_START';
export const SEARCH_PHONE_SUCCESS = 'SEARCH_PHONE_SUCCESS';
export const SEARCH_PHONE_FAILURE = 'SEARCH_PHONE_FAILURE';

export const SAVE_NEW_PHONE_START = 'SAVE_NEW_PHONE_START';
export const SAVE_NEW_PHONE_SUCCESS = 'SAVE_NEW_PHONE_SUCCESS';
export const SAVE_NEW_PHONE_FAILURE = 'SAVE_NEW_PHONE_FAILURE';